### ISSUE TITLE
Error: Value cannot be null. (Parameter 's')

### ISSUE THREAD

**Issue by Cyruz143** [BytexDigital/SteamCLI#1]
When calling steamCLI with the below:
```
.\steamcli.exe --username=xxx --password="xxx" --app-download --targetdir=xxx --branch=public --os=windows --appid=233780 --depotid=233782--synctarget
```

I get the following error:
```
Attempting to start download of app 233780, depot 233782... Error: Value cannot be null. (Parameter 's')
```

Suspect it's due to steam API changes.

**Comment by Foxlider** [comment]
1. Use the proper issue template
2. Update to the latest version

**Comment by Cyruz143** [comment]
> 1. Use the proper issue template
> 
>     2. Update to the latest version

There isn't an issue template I can see for this repo and I'm on 1.0.3.0

```
PS C:\xxx\xxx> .\steamcli.exe --help
steamcli 1.0.3.0
Copyright (C) 2023 Bytex Digital UG (haftungsbeschränkt)
```

**Comment by Foxlider** [comment]
Oh shoot, I thought this was a different repo, my bad

Make sure your password is correct, then
If you are positively sure, this might be due to recent changes in Steam's API and might have to wait for an update for SteamCLI

**Comment by Cyruz143** [comment]
Details should all be fine, it's a headless account that's just used on the server.

> Oh shoot, I thought this was a different repo, my bad
> 
> Make sure your password is correct, then If you are positively sure, this might be due to recent changes in Steam's API and might have to wait for an update for SteamCLI

Checked it from the GUI client, logins fine from the same machine. As I said, suspect API changes need rolling to steamCLI.

**Comment by RyanTT** [comment]
Underlying library hasn't been updated in some time, so it's most likely a versioning issue. Will get to it soon.

**Comment by RyanTT** [comment]
Please try this new release https://github.com/BytexDigital/SteamCLI/releases/tag/1.0.4.0

**Comment by Cyruz143** [comment]
> Please try this new release https://github.com/BytexDigital/SteamCLI/releases/tag/1.0.4.0

Works perfectly, ty!
