### ISSUE TITLE
Stuck on 'Connecting to Steam as <user>'

### ISSUE THREAD

**Issue by Cyruz143** [BytexDigital/SteamCLI#2]
Seems to have happened today.

Tried from 2 different machines and 2 different accounts, both hang at the same spot (login). Left for 5 minutes, no progress, errors or timeout etc.

Input:
```
.\steamcli.exe --username=<username>--password=<password> --app-download --targetdir=D:\test --branch=public --os=windows --appid=233780 --depotid=233781 --synctarget
```

Output:
```
Connecting to Steam as <username>...
```

Version:
```
PS C:\Users\Cyruz\Downloads> .\steamcli.exe --version
steamcli 1.0.4.0
```

**Comment by RyanTT** [comment]
Hey, thanks for reporting this. The issue has been fixed in the underlying library, I'll try to get a new version of SteamCLI out with it today.

**Comment by RyanTT** [comment]
Update published at https://github.com/BytexDigital/SteamCLI/releases/tag/1.0.5.0

Let me know if it works for you

**Comment by Cyruz143** [comment]
Verified and working, ty!
